{  
  "Version":"2012-10-17",
  "Statement":[  
     {  
        "Effect":"Allow",
        "Action":[  
           "sts:AssumeRole"
        ],
        "Resource":[  
           "arn:aws:iam::*:role/${var.project}-management-org-admin",
           "arn:aws:iam::${var.aws_account_id}:role/${var.project}-full-admin-management"
        ]
     }
  ]
}