{  
  "Version":"2012-10-17",
  "Statement":[  
     {  
        "Effect":"Allow",
        "Action":[  
           "sts:AssumeRole"
        ],
        "Resource":[  
           "arn:aws:iam::${aws_account_id}:role/${project}-management-org-admin"
        ]
     }
  ]
}